// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Golang-labs-ip/Golang-lab3/server/tablets"
)

func ComposeApiServer(port HttpPortNumber) (*TabletApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := tablets.NewStore(db)
	httpHandlerFunc := tablets.HTTPHandler(store)
	tabletApiServer := &TabletsApiServer{
		Port:             port,
		TabletsHandler: httpHandlerFunc,
	}
	return tabletApiServer, nil
}
